spring.application.name=backend


# Aktives Profil (Standard: dev)
spring.profiles.active=dev

# JPA / Hibernate
spring.jpa.hibernate.ddl-auto=validate
spring.jpa.open-in-view=false

# Flyway
spring.flyway.enabled=true